from tkinter import *
from math import *

def click(event):
    global scvalue 
    text = event.widget.cget("text")
    if text == "=":
        var=((screen.get()).replace("e", "2.71828"))
        vaar=((var).replace("PI", "3.1415926535"))
        if scvalue.get().isdigit():
            value = int(scvalue.get())
        else:
            try:
                value = eval(vaar)                
            except Exception as e:
                value="Error"
        scvalue.set(value)
        screen.update()
    elif text =="clear":
        scvalue.set("")
        screen.update()
    else:
        scvalue.set(scvalue.get()+text)
        screen.update()



root = Tk()
root.geometry("560x514")
root.resizable(FALSE,FALSE)
root.title("Smart-Calculator")
root.wm_iconbitmap("Calculator.ico")

scvalue = StringVar()
scvalue.set("")
screen = Entry(root, textvar=scvalue, font="Helvetica 40 " )
screen.configure( background="white smoke")
screen.pack(fill=X, ipadx=8, padx=5, pady=5)

f = Frame(root, bg="light gray")
b = Button(f,text="clear",font="Helvetica 25 ", padx=27,pady=5)
b.pack(side= LEFT, padx=2, pady=2)
b.bind("<Button-1>",click)
b.configure( background="silver")
b = Button(f,text="sin",font="Helvetica 25 ", padx=16,pady=5)
b.pack(side= LEFT, padx=2, pady=2)
b.bind("<Button-1>",click)
b.configure( background="silver")
b = Button(f,text="cos",font="Helvetica 25 ", padx=16,pady=5)
b.pack(side= LEFT, padx=2, pady=2)
b.bind("<Button-1>",click)
b.configure( background="silver")
b = Button(f,text="tan",font="Helvetica 25 ", padx=16,pady=5)
b.pack(side= LEFT, padx=2, pady=2)
b.bind("<Button-1>",click)
b.configure( background="silver")
b = Button(f,text="/",font="Helvetica 25 ", padx=16,pady=5)
b.pack(side= LEFT, padx=2, pady=2)
b.bind("<Button-1>",click)
b.configure( background="silver")
f.pack()

f = Frame(root, bg="light gray")
b = Button(f,text="(",font="Helvetica 30 ", padx=27,pady=5)
b.pack(side= LEFT, padx=2, pady=2)
b.bind("<Button-1>",click)
b.configure( background="silver")
b = Button(f,text="9",font="Helvetica 30 ", padx=27,pady=5)
b.pack(side= LEFT, padx=2, pady=2)
b.bind("<Button-1>",click)
b.configure( background="silver")
b = Button(f,text="8",font="Helvetica 30 ", padx=27,pady=5)
b.pack(side= LEFT, padx=2, pady=2)
b.bind("<Button-1>",click)
b.configure( background="silver")
b = Button(f,text="7",font="Helvetica 30 ", padx=27,pady=5)
b.pack(side= LEFT, padx=2, pady=2)
b.bind("<Button-1>",click)
b.configure( background="silver")
b = Button(f,text="*",font="Helvetica 30 ", padx=27,pady=5)
b.pack(side= LEFT, padx=2, pady=2)
b.bind("<Button-1>",click)
b.configure( background="silver")
f.pack()


f = Frame(root, bg="light gray")
b = Button(f,text=")",font="Helvetica 30 ", padx=27,pady=5)
b.pack(side= LEFT, padx=2, pady=2)
b.bind("<Button-1>",click)
b.configure( background="silver")
b = Button(f,text="6",font="Helvetica 30 ", padx=27,pady=5)
b.pack(side= LEFT, padx=2, pady=2)
b.bind("<Button-1>",click)
b.configure( background="silver")
b = Button(f,text="5",font="Helvetica 30 ", padx=27,pady=5)
b.pack(side= LEFT, padx=2, pady=2)
b.bind("<Button-1>",click)
b.configure( background="silver")
b = Button(f,text="4",font="Helvetica 30 ", padx=27,pady=5)
b.pack(side= LEFT, padx=2, pady=2)
b.bind("<Button-1>",click)
b.configure( background="silver")
b = Button(f,text="-",font="Helvetica 30 ", padx=27,pady=5)
b.pack(side= LEFT, padx=2, pady=2)
b.bind("<Button-1>",click)
b.configure( background="silver")


f.pack()

f = Frame(root, bg="light gray")
b = Button(f,text="PI",font="Helvetica 30 ", padx=24,pady=5)
b.pack(side= LEFT, padx=2, pady=2)
b.bind("<Button-1>",click)
b.configure( background="silver")
b = Button(f,text="3",font="Helvetica 30 ", padx=24,pady=5)
b.pack(side= LEFT, padx=2, pady=2)
b.bind("<Button-1>",click)
b.configure( background="silver")
b = Button(f,text="2",font="Helvetica 30 ", padx=24,pady=5)
b.pack(side= LEFT, padx=2, pady=2)
b.bind("<Button-1>",click)
b.configure( background="silver")
b = Button(f,text="1",font="Helvetica 30 ", padx=24,pady=5)
b.pack(side= LEFT, padx=2, pady=2)
b.bind("<Button-1>",click)
b.configure( background="silver")
b = Button(f,text="+",font="Helvetica 30 ", padx=24,pady=5)
b.pack(side= LEFT, padx=2, pady=2)
b.bind("<Button-1>",click)
b.configure( background="silver")
f.pack()

f = Frame(root, bg="light gray")
b = Button(f,text="e",font="Helvetica 28 ", padx=27,pady=5)
b.pack(side= LEFT, padx=2, pady=2)
b.configure( background="silver")
b.bind("<Button-1>",click)
b.configure( background="silver")
b = Button(f,text="0",font="Helvetica 28 ", padx=27,pady=5)
b.pack(side= LEFT, padx=2, pady=2)
b.bind("<Button-1>",click)
b.configure( background="silver")
b = Button(f,text=".",font="Helvetica 28 ", padx=27,pady=5)
b.pack(side= LEFT, padx=2, pady=2)
b.bind("<Button-1>",click)
b.configure( background="silver")
b = Button(f,text="%",font="Helvetica 28 ", padx=27,pady=5)
b.pack(side= LEFT, padx=2, pady=2)
b.bind("<Button-1>",click)
b.configure( background="silver")
b = Button(f,text="=",font="Helvetica 28 ", padx=27,pady=5)
b.pack(side= LEFT, padx=2, pady=2)
b.bind("<Button-1>",click)
b.configure( background="silver")
f.pack()

root.mainloop()